import requests
import concurrent.futures
import sys
import os
import time
from colorama import Fore, Style, init

init(autoreset=True)

DATABASE_URLS = [
    "https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock_project/resources/data.json",
    "https://raw.githubusercontent.com/sherlock-project/sherlock/main/sherlock_project/resources/data.json",
    "https://raw.githubusercontent.com/sherlock-project/sherlock/master/sherlock/resources/data.json"
]

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
}

def load_database():
    print(f"{Fore.YELLOW}[*] Veritabanı sunucudan çekiliyor...{Style.RESET_ALL}")
    for url in DATABASE_URLS:
        try:
            response = requests.get(url, timeout=10)
            if response.status_code == 200:
                data = response.json()
                print(f"{Fore.GREEN}[+] Veritabanı yüklendi! (Site Sayısı: {len(data)}){Style.RESET_ALL}")
                return data
        except Exception:
            continue 
    print(f"{Fore.RED}[!] HATA: Sunuculara ulaşılamadı.{Style.RESET_ALL}")
    sys.exit()

def check_site(site_name, site_data, username):
    try:
        url = site_data.get("url").replace("{}", username)
        error_type = site_data.get("errorType")
        error_msg = site_data.get("errorMsg")
        exists = False

        req = requests.get(url, headers=HEADERS, timeout=10, allow_redirects=True)

        if error_type == "status_code":
            if req.status_code != 404:
                exists = True
        elif error_type == "message":
            if req.status_code != 404:
                if isinstance(error_msg, list):
                    if not any(msg in req.text for msg in error_msg):
                        exists = True
                elif isinstance(error_msg, str):
                    if error_msg not in req.text:
                        exists = True
                else:
                     if str(error_msg) not in req.text:
                         exists = True
        elif error_type == "response_url":
            if 200 <= req.status_code < 300 and req.url == url:
                 exists = True
    except:
        return None 

    return {"site": site_name, "url": url} if exists else None

def generate_dorks(username):
    return [
        f"https://www.google.com/search?q=site:pastebin.com+OR+site:github.com+\"{username}\"",
        f"https://www.google.com/search?q=filetype:txt+OR+filetype:pdf+OR+filetype:csv+\"{username}\"",
        f"https://www.google.com/search?q=\"{username}\"+password+OR+pass+OR+login",
        f"https://www.google.com/search?q=inurl:\"{username}\""
    ]

def save_report(username, found_list, dorks):
    filename = f"{username}_report.txt"
    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"==================================================\n")
        f.write(f" DIJITAL GOLGE RAPORU: {username}\n")
        f.write(f" Tarih: {time.strftime('%d/%m/%Y %H:%M')}\n")
        f.write(f"==================================================\n\n")
        
        f.write(f"[+] BULUNAN PROFİLLER ({len(found_list)} Adet):\n")
        for item in found_list:
            f.write(f" - {item['site']:<20} : {item['url']}\n")
            
        f.write(f"\n==================================================\n")
        f.write(f"[!] GOOGLE DORK LİNKLERİ:\n\n")
        for dork in dorks:
            f.write(f" -> {dork}\n")
            
        f.write(f"\n==================================================\n")
        f.write(f"Generated by EGNAKE v5.0\n")
        
    print(f"\n{Fore.GREEN}[OK] Rapor oluşturuldu: {os.getcwd()}{os.sep}{filename}{Style.RESET_ALL}")

def main():
    banner = f"""{Fore.CYAN}
    ███████╗ ██████╗ ███╗   ██╗ █████╗ ██╗  ██╗███████╗
    ██╔════╝██╔════╝ ████╗  ██║██╔══██╗██║ ██╔╝██╔════╝
    █████╗  ██║  ███╗██╔██╗ ██║███████║█████╔╝ █████╗  
    ██╔══╝  ██║   ██║██║╚██╗██║██╔══██║██╔═██╗ ██╔══╝  
    ███████╗╚██████╔╝██║ ╚████║██║  ██║██║  ██╗███████╗
    ╚══════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝
    {Fore.WHITE}  OSINT ARAMA ARACI - EGNAKE v5.0
    {Style.RESET_ALL}"""
    
    print(banner)
    sites_db = load_database()
    
    username = input(f"\n{Fore.YELLOW}[?] Hedef Kullanıcı Adı: {Style.RESET_ALL}").strip()
    if not username: return

    print(f"\n{Fore.CYAN}[*] {username} taranıyor...{Style.RESET_ALL}\n")

    found_list = []
    
    with concurrent.futures.ThreadPoolExecutor(max_workers=50) as executor:
        futures = [executor.submit(check_site, name, data, username) for name, data in sites_db.items()]

        for future in concurrent.futures.as_completed(futures):
            res = future.result()
            if res:
                found_list.append(res)
                print(f"[{Fore.GREEN}+{Style.RESET_ALL}] {Fore.GREEN}{res['site']:<20}{Style.RESET_ALL} : {res['url']}")

    print(f"\n{Fore.CYAN}=================================================={Style.RESET_ALL}")
    print(f"{Fore.YELLOW}[i] TARAMA ÖZETİ ({len(found_list)} Profil Bulundu){Style.RESET_ALL}")
    print(f"{Fore.CYAN}=================================================={Style.RESET_ALL}")
    
    found_names = [item['site'] for item in found_list]
    print(f"{Fore.WHITE}{', '.join(found_names)}{Style.RESET_ALL}")

    dorks = generate_dorks(username)
    
    print(f"\n{Fore.CYAN}=================================================={Style.RESET_ALL}")
    print(f"{Fore.RED}[!] GOOGLE DORK LİNKLERİ:{Style.RESET_ALL}")
    for dork in dorks:
        print(f"{Fore.BLUE} -> {dork}{Style.RESET_ALL}")

    save_report(username, found_list, dorks)

if __name__ == "__main__":

    main()
